awslabs/aws-servicebroker

templates/sns/README.md, templates/sns/template.yaml
*Description of changes:*
Add some options of `DeliveryPolicy`.
https://docs.aws.amazon.com/sns/latest/dg/DeliveryPolicies.html
https://aws.amazon.com/jp/blogs/compute/managing-amazon-sns-subscription-attributes-with-aws-cloudformation/
=> feat(sns): add delivery options

pkg/broker/util.go, pkg/broker/util_test.go
Cleans up the `prescribeOverrides` implementation.
With the original implementation, the `TestPrescribeOverrides` test was failing about 10% of the time like this:
```
--- FAIL: TestPrescribeOverrides (0.00s)
util_test.go:141: 
Error Trace:	util_test.go:141
Error:      	Not equal: 
expected: []v2.Service{v2.Service{ID:"test", Name:"test", Description:"test", Tags:[]string(nil), Requires:[]string(nil), Bindable:false, BindingsRetrievable:false, PlanUpdatable:(*bool)(nil), Plans:[]v2.Plan{v2.Plan{ID:"testplan", Name:"testplan", Description:"testplan", Free:(*bool)(nil), Bindable:(*bool)(nil), Metadata:map[string]interface {}(nil), Schemas:(*v2.Schemas)(0xc420387b40)}}, DashboardClient:(*v2.DashboardClient)(nil), Metadata:map[string]interface {}(nil)}}
actual  : …
```
=> Refactor prescribeOverrides

pkg/broker/api_test.go, pkg/broker/awsbroker_test.go
Adds tests for `Unbind`, increasing coverage to 92.9%.
```
--- PASS: TestUnbind (0.00s)
--- PASS: TestUnbind/error_getting_binding (0.00s)
--- PASS: TestUnbind/binding_not_found (0.00s)
--- PASS: TestUnbind/success (0.00s)
--- PASS: TestUnbind/error_getting_instance (0.00s)
--- PASS: TestUnbind/instance_not_found (0.00s)
--- PASS: TestUnbind/error_detaching_role_policy (0.00s)
--- PASS: TestUnbind/detach_role_policy (0.00s)
--- PASS: TestUnbind/role_not_found (0.00s)
```
=> Add Unbind tests

packaging/helm/aws-servicebroker/templates/broker-deployment.yaml, pkg/broker/aws_sdk.go
- Updates the Helm template to set `region`.
- Allows overriding the target region with a param.
Fixes #33.
=> Allow overriding the target region

pkg/broker/awsbroker.go, pkg/broker/util.go, pkg/broker/util_test.go, scripts/start_broker.sh
`prescribeOverrides` now verifies that `params["required"]` is not `nil` before asserting that it is a `[]string`. 
Also ensures that `params["required"]` is not an empty slice when `prescribeOverrides` is `false`.
Fixes #32.
=> Do not panic when there are no required params

packaging/helm/aws-servicebroker/templates/broker-deployment.yaml, packaging/helm/aws-servicebroker/values.yaml
Add `annotations` to helm values.
When using [kiam](https://github.com/uswitch/kiam), it needs to annotate to pod.
aws-servicebroker needs the high privilege.
For security, out project uses not IAM role for EC2 instance but IAM role for Pod by using kiam.
```
annotations:
iam.amazonaws.com/role: awsservicebroker-role
```
```
$ helm install packaging/helm/aws-servicebroker/ --name aws-servicebroker --set annotations."iam\.amazonaws\.com/role"=awsservicebroker-role --namespace aws-sb
```
=> Add annotations to helm values

packaging/openshift/deploy.sh
This should resolve issues with #49 as it encodes a user's secrets when it creates them in OpenShift. 
Fixes #49 
This was the modification I made to the script in order to fix the issues I had run into during a deployment. It corrects the manual changes one has to make if you don't have such a commit. 
=> resolves #49, as takes unencoded data from the user

templates/dynamodb/template.yaml
Updates the `dynamodb` template to use `HashAttributeType` and `RangeAttributeType` instead of hardcoding the data types to `S`.
Fixes #58.
=> [dynamodb] Use HashAttributeType and RangeAttributeType

pkg/broker/api.go, pkg/broker/api_test.go, pkg/broker/awsbroker_test.go, pkg/broker/util.go
If an attempt is made to update an instance with no updatable parameters, the update will fail and the instance will be left in status `Failed`. This change allows the instance to be updated back to its original parameters to get its status back to `Ready`.
This also adds tests for `Update`, increasing coverage from 0% to 96.4%.
Fixes #54.
(We should create a new issue if the `rds` class needs some updatable parameters.)
=> Remove check for no updatable parameters

packaging/helm/aws-servicebroker/templates/broker.yaml, packaging/helm/aws-servicebroker/values.yaml
- cluster.local is the default domain.  Some clusters may change this
value.
Signed-off-by: Dan Wendorf <dan.wendorf@opendoor.com>
Our Kubernetes cluster uses a non default cluster domain and would like to use this chart to install the aws service broker
Fixes #
Ran `helm install`
Run `helm …
=> Make cluster domain configurable

pkg/broker/awsbroker.go, pkg/broker/types.go, pkg/broker/util.go
When set to `True`, output keys from CloudFormation are not converted to
screaming snake case before added to service bindings.
This is useful when needing to be compatible with existing libraries.
Many existing libraries assume certain names for parameters in service bindings, e.g. the CloudFoundry Spring Connectors for Redis look for `Uri` and `Url`.
Currently the broker always converts the names in the CloudFormation template to `SCREAMING_SNAKE_CASE` (my life is enriched from now knowing this term).
This PR allows some service metadata to specify that this should not happen. If not specified, the current behaviour will continue.
Fixes #78
Read, built, ran, tested creation of new service with this specified.
Tested creation of service that did not specify this.
Add:
```yaml …
```
=> Add `OutputsAsIs` optional field to metadata for a service

packaging/helm/aws-servicebroker/templates/broker-deployment.yaml
I got the following error.
```
F1217 07:39:28.650156       1 main.go:53] open /var/run/awssb/awssb.crt”: no such file or directory
```
It includes unnecessary double quotes at the end of the line.
Nothing
```
$ helm install --namespace aws-sb packaging/helm/aws-servicebroker
```
Nothing
```
$ helm install --namespace aws-sb packaging/helm/aws-servicebroker
$ kubectl logs aws-servicebroker-XXXXXXXXXX-XXXXX -n aws-sb
```
=> fix(helm): remove double quotes

templates/rdspostgresql/template.yaml
When setting `StorageEncrypted=false`, the cloudformation template still try to provision an encrypted postgres DB instance, due to KMS key provisionning.
I disabled the KMS key provisionning when `StorageEncrypted=false` in the same way as rdsmysql cloudformation template.
None
```
aws cloudformation create-stack --capabilities CAPABILITY_IAM \
--template-body file://templates/rdspostgresql/template.yaml \
--stack-name rdspostgres-custom-noencryption-test --output json \
--region eu-west-1 \
--parameters ParameterKey=AccessCidr,ParameterValue=10.0.0.0/8 \
ParameterKey=VpcId,ParameterValue=vpc-1234 \
ParameterKey=MasterUsername,ParameterValue=toto \
ParameterKey=StorageEncrypted,ParameterValue=false
```
not tested trough aws-servicebroker
By submitting this pull request, I confirm that my …
=> Make encryption optionnal for rdspostgresql

docs/getting-started-k8s.md, packaging/helm/aws-servicebroker/templates/_helpers.tpl, packaging/helm/aws-servicebroker/templates/broker.yaml, packaging/helm/aws-servicebroker/values.yaml
Allows the service broker to be deployed as a [Namespaced Service Broker](https://svc-cat.io/docs/namespaced-broker-resources/).
Fixes #95
Validated with `helm template` rendering and deploying to test instance
* ClusterServiceBroker still default as `deployClusterServiceBroker` is still default value of `true`
* Deploy namespaced broker by setting `deployNamespacedServiceBroker` to `true`, i.e. `--set deployNamespacedServiceBroker=true`
* Setting both values to false results in no broker being created
=> Added helm value for deploying a NamespacedServiceBroker

templates/rdsmysql/template.yaml
Added missing Version2Family mappings
This PR patches the RDS MySQL Cloud Formation template by adding the missing family mapping in the cloud formation template
Failure to provision rds mysql with latest 5.7 family as it cannot find the family mapping 
=> Update rds mysql template.yaml

templates/auroramysql/template.yaml, templates/documentdb/README.md, templates/documentdb/template.yaml, templates/rdsoracle/README.md
1. New DocumentDB template for Service Broker, with ReadMe
2. In OracleRDS Readmemd, missing a param setting in docs
3. In AuroraMySQL, remove the default value on the AccessCIDR
Tested DocumentDB launching cluster with 1 and multiple instances (1x Writer 2x Reader)
Tested connection to the endpoints for the cluster.
=> New DocumentDB Template for service broker

templates/mq/template.yaml
Password is invalid. Enter a password 12 to 250 characters long. (Service: AmazonMQInternal; Status Code: 400; Error Code: BadRequestException; R)
Caused by the value being set to auto instead of Auto in the Service Broker service plans.
Corrected by fixing the AWS::ServiceBroker::Specification ServicePlans in the template
=> Fix casing for Password value from auto to Auto - causing password error

packaging/helm/aws-servicebroker/templates/broker-credentials.yaml, packaging/helm/aws-servicebroker/templates/broker-deployment.yaml, packaging/helm/aws-servicebroker/values.yaml
In our setup we deploy secret using https://github.com/bitnami-labs/sealed-secrets. For this to work properly helm-charts need to not deploy their own secrets but instead configure their templates to use an existing secret. This PR adds this feature to aws-servicebroker.
none
helm install on a local test-cluster
none
```
kubectl create secret ...
helm install -f values.yaml . --name aws-broker-test
```
=> allow helm chart to be deployed with an existing secret

templates/dynamodb/ci/config.yml, templates/dynamodb/template.yaml
Updated to use the hash and range attribute type input parameters for defining the types in the resource > attribute definitions
Fixes #164
- Spin up a Kubernetes cluster
- Deploy the AWS service broker (using the updated template for the dynamodb service)
- Provision a table using a Numerical Hash or Range AttributeType
- Check using the AWS console that the table is provisioned with the correct type
=> Fix the dynamodb template to support numerical and boolean key attribute types

templates/elasticsearch/README.md
The list of provided bind credentails for the elasticsearch service appears to be incorrect, so I have altered the list to the credentials returned by inspecting the binding with svcat.
=> correct documentation to show correct bind credentials for elasticsearch

.gitignore, Makefile, pkg/broker/awsbroker.go, pkg/broker/cfcreds.go, pkg/broker/types.go, pkg/broker/util.go
added final mapping for CloudFoundry
move cred generation to seperate file
fix up cred gen error, add temp debugging
fix postgre cred gen
fix mysql and mariadb cred gen
fixed s3 credentials
this add support for spring applications that do not autobuild uris.  this still requires the password generating lambda to be fixed.
Fixes #
these were testing using java applications that use the autoprovided uri fields, etc
By submitting this pull request, I confirm that my …
=> Support vCapServices

packaging/openshift/deploy.sh
Fixing the deploy.sh script for OpenShift ... Adding it to release-v1.0.1 branch. 
This means that the instructions on https://github.com/awslabs/aws-servicebroker/blob/master/docs/getting-started-openshift.md (master) should fetch the correct script. 
I tested this curl command returned the correct script content:
curl https://raw.githubusercontent.com/sjbylo/aws-servicebroker/release-v1.0.1/packaging/openshift/deploy.sh
=> Fixed the deploy.sh script for openshift 4 - add to release-v1.0.1 branch.  

templates/s3/template.yaml
This PR fixes a typo in the description of a stack parameter for provisioning S3 buckets.
Textual change to description should not affect any logic.
=> Fix typo in EnableLogging description

packaging/helm/aws-servicebroker/templates/broker-credentials.yaml
When using target role for authentication helm 3 raises a validation error on generated secrets since accesskeyid and secretkey are blank. Adding the quotes make sure the generated files pass validation
Fixes https://github.com/awslabs/aws-servicebroker/issues/179
Installed aws-servicebroker successfully with modified charts using helm 2 as well as helm 3
NA
* Checkout the branch
* cd packaging
* make sure helm 3 is installed and install aws-service broker by running below command
```helm install -n aws-sb aws-servicebroker ./aws-servicebroker --wait --version 1.0.1 --set aws.region=us-east-1 --set aws.targetrolename=aws_service_broker-role```
=> Change to support helm 3 with out accesskeyid and secretkey

docs/index.yaml, packaging/helm/aws-servicebroker/Chart.yaml, packaging/helm/aws-servicebroker/templates/_helpers.tpl, packaging/helm/aws-servicebroker/templates/broker-deployment.yaml, packaging/helm/aws-servicebroker/values.yaml
- added the deployment.apiVersion template commonly used in helm/stable
repos to determine correct apiVersion of deployments
- added a nodeSelector option on the Deployment
- added extraEnv array on values so extra environment variables can be
added to the deployment
The apiVersion on the deployment is especially useful for k8s versions 1.16+ since the current chart is using `extensions/v1beta1` which has been completely removed in k8s 1.16 and deprecated since k8s v1.9. 
Fixes #189 
Fixes: #187 
Manually tested with my own values file. Very simple to do and I have written plenty of charts with the same features I just added. 
I will be publicly hosting the helm repo on my fork of this project if anyone is interested in using it. 
Simply create a file called `values.yaml` like so:
```yaml …
```
=> helm chart features added for stability and usability

templates/documentdb/template.yaml
Typo in DocumentDB ->BackupRetentionPeriod.
MinValue was 1, updated to allow for 0
Error reported by user
=> update BackupRetentionPeriod minvalue param from 1 to 0

templates/documentdb/template.yaml
Updating the value in dev pland for BackupRetention from 0 to 1 in inline with minimums per AWS docs for DocumentDb
=> Update Dev plan: BackupRetention Period to 1

packaging/openshift/aws-servicebroker.yaml
Updated "apiVersion: extensions/v1beta1" to "apiVersion: apps/v1" in "kind: Deployment" after receiving the following error: unable to recognize no matches for kind "Deployment" in version "extensions/v1beta1"
Resolve issue with Deployment in OpenShift: unable to recognize no matches for kind "Deployment" in version "extensions/v1beta1"
Validated change with successful creation of Deployment (see attached)
=> Update Deployment apiVersion

pkg/broker/api.go, pkg/broker/api_test.go, pkg/broker/awsbroker.go, pkg/broker/awsbroker_test.go, pkg/broker/types.go, pkg/broker/types_test.go
Add support for service plan costs defined in the OSB convention by including in the CloudFormation template a "Costs" (note the "s") key alongside the existing "Cost" key in the ServicePlan definition, and by modifying the `Db.ServiceDefinitionToOsb` method to take account of this new key.
I've deliberately left he old "Cost" key because, I assume this was designed to avoid having to update the template every time the costs change upstream.  In this case, we'd like to present costs to our internal customers via Stratos, and we'll need to use the OSB convention instead. 
Fixes #222 
I slightly refactored the `Db.ServiceDefinitionToOsb` method, pulling out a new, private, `Db.servicePlanToOSBPlan` which I was able to directly test via a unit test.  I also added a test to a new …
=> Support osb costs convention

pkg/broker/types.go, pkg/broker/types_test.go
This PR makes a minor correction to the JSON output for a Service Plan in the catalogue.  Previously we added support for the costs convention used by some applications (e.g. Stratos, CloudFoundry).   Unfortunately, we tested this code with clients that were case-insensitive, but in practice CloudFoundry expects the keys "amount" and "unit" to be lowercase.  This PR achieves that by adding JSON annotations to the structure that are used by `encoding/json` when marshalling the struct. 
Fixes #244 
I have added a sub-test to the existing unit test which tests that the JSON output format is correct.  
Additionally, I have deployed this in our Cloud Foundry environment and seen that the `cf marketplace -e <service name>` command produces output including the cost data, z.B.: 
```
broker: …
```
=> Output keys from OSB costs convention to be lower-case as CF expects

templates/athena/template.yaml, templates/auroramysql/template.yaml, templates/aurorapostgresql/template.yaml, templates/cognito/template.yaml, templates/documentdb/template.yaml, templates/dynamodb/template.yaml, templates/elasticache/template.yaml, templates/elasticsearch/template.yaml, templates/emr/template.yaml, templates/kinesis/template.yaml, templates/kms/template.yaml, templates/lex/template.yaml, templates/mq/template.yaml, templates/polly/template.yaml, templates/rdsmariadb/template.yaml, templates/rdsmssql/template.yaml, templates/rdsmysql/template.yaml, templates/rdsoracle/template.yaml, templates/rdspostgresql/template.yaml, templates/redshift/template.yaml, templates/rekognition/template.yaml, templates/s3/template.yaml, templates/sns/template.yaml, templates/sqs/template.yaml, templates/translate/template.yaml
This PR update python version for lambdas from 2.7 (that is currently is not supported by AWS) to 3.9
Since AWS is not supporting lambdas with python 2.7 runtime, AWS service broker should be updated accordingly.
=> Change python version to 3.9
