build-tools/README.md

*Description of changes:*
Added readme to build-tools directory.

Add AWS APB building instructions to build-tools dir

---

templates/sqs/template.yaml

*Issue #, if available:*
*Description of changes:*
The description differs only for SQS
```
$ kubectl plugin svcat get classes
NAME         NAMESPACE                   DESCRIPTION
+------------------+-----------+----------------------------------------------+
dh-emr                         AWS Service Broker - Amazon EMR
dh-dynamodb                    AWS Service Broker - Amazon DynamoDB
dh-rdsmariadb                  AWS Service Broker - Amazon RDS for MariaDB
dh-rekognition                 AWS Service Broker - Amazon Rekognition
dh-athena                      AWS Service Broker - Amazon Athena.
dh-sqs                         AWS Servicebroker - Amazon SQS
dh-kms                         AWS Service Broker - KMS Key
dh-rdspostgresql               AWS Service Broker - Amazon RDS for
... …
```

fix sqs description

---

templates/s3/README.md
templates/s3/template.yaml

*Description of changes:*
Parameterize `PreventDeletion`.
I wanted to write something like:
```
DeletionPolicy: !Ref DeletionPolicy
```
However, "Parameter" can't be used with "DeletionPolicy"...
https://forums.aws.amazon.com/message.jspa?messageID=560586
The above template got the following error.
```
An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: Every DeletionPolicy member must be a string.
```
I used the workaround like this.
https://forums.aws.amazon.com/message.jspa?messageID=859017#859017
Nested stack could be used , but it seemed that specification of SBArtifactS3Bucket might be complicated.
Thanks.

feat(s3): add PreventDeletion parameter

---

docs/getting-started-pcf.md

added slight intro text updates to reflect status

---

docs/README.md
docs/getting-started-k8s.md

Fix typo in the docs

---

docs/install_prereqs.md

Remove duplicated permission

---

docs/install_prereqs.md
setup/prerequisites.yaml

For the operator being able to retrieve stack events on failed provisioning, this action is required.

Allow DescribeStackEvents

---

templates/sqs/template.yaml

All other services use "AWS Service Broker" in their description. Fixing this entry for consistency.
Fixes #

Fixing typo.

---

docs/README.md

Changed Currentently to Currently
Fixed a single typo in docs/README.md - Changed "Currentently" to "Currently"
Fixes #
No open issues or PRs for this.  Just a little typo.
Viewed the Readme file to verify fix
View docs/README.md to view fix
By submitting this pull request, I confirm that my …

Fixed single typo in docs/README.md

---

pkg/broker/aws_sdk.go
pkg/broker/awsbroker.go
pkg/broker/awsbroker_test.go
pkg/broker/types.go
pkg/broker/util.go

This PR adds support for AWS China region
Fixes #112 
Already tested in AWS China ningxia region. 

Add support for AWS China partition

---

docs/README.md
templates/auroramysql/README.md
templates/auroramysql/template.yaml
templates/aurorapostgresql/README.md
templates/aurorapostgresql/template.yaml
templates/rdsmssql/README.md
templates/rdsmssql/template.json
templates/rdsmssql/template.yaml

RDS Aurora MySQL
RDS Aurora Postgress
RDS MS SQL 
CFN templates + readme
First iteration of templates for these services.
To be vetted, and tested by author.

RDS Aurora, Meta/Docs gen tool

---

docs/examples/example-main.yaml

The template fails if this is not fixed with the correct resource name "S3Bucket".
Fixes #
Just launched the template.

S3Bucket resource name is case sensitive and Actions list on IAM Policy resources

---

templates/rdsoracle/README.md
templates/rdsoracle/template.yaml

New Service Broker template for RDS Oracle. 
Contains functionality for Read Replicas and Oracle generic setup
Ran the template through MultiAZ true,false. Read Replicas (0, 1 and 2), Differing versions and licensing per documentation. 

RDS Oracle Service Broker Template + readme

---

templates/auroramysql/template.yaml
templates/aurorapostgresql/template.yaml
templates/documentdb/template.yaml
templates/elasticache/template.yaml
templates/elasticsearch/template.yaml
templates/rdsmariadb/template.yaml
templates/rdsmssql/template.yaml
templates/rdsmysql/template.yaml
templates/rdsoracle/template.yaml
templates/rdspostgresql/template.yaml
templates/redshift/template.yaml
templates/sqs/template.yaml

As recommended in RFC default values should match the schema, so this PR fixes some Number values which have string defaults.
Fixes #131 

Change default Number values to numbers

---

packaging/openshift/deploy.sh

Changed the script so it will also work on OpenShift version 4.1

Fixed deploy.sh script for OpenShift 4.1

---

docs/README.md

Update typo in doc's README.md

---

docs/README.md

Typo found and fixed in README.md

---

docs/README.md

Fix docs for parameter overrides.
Fixes #177 
Visual check
None
N/A

Issue-177: fix documentation for parameter overrides

---

templates/elasticsearch/README.md

This PR improves visibility of different parameter types in the readme
NA
NA

Make parameter types more visible

---

pkg/broker/api.go

This PR improves the logs that are output when the log verbosity is set to 10, and an error occurs in provisioniing a new service. 
Fixes #168 
I built a new tile and deployed it into our pivotal cloud foundry sandbox.  We are experiencing issues similar to issue #141 and previously the logs fro provisioning would log the `StackName`, `TargetURL` and `Capabilities` as memory addresses, now I see all the string values as expected. 
* Deploy the aws-servicebroker as you normally would, making sure to configure the log verbosity to 10.
* Cause a Provision request to be made against the aws-servicebroker.
* Check the aws-servicebroker logs, see that StackName, TemplateURL and Capabilities are all human readable values, not memory addresses
By submitting this pull request, I confirm that my …

Log values, not pointers to them

---

functions/generate_password/lambda_function.py

This PR changes the password generating lambda to remove characters that would break URI's
Fixes #
this is lambda is currently deployed in my production account

fix password for applications that build their own URI's

---

docs/getting-started-k8s.md

HELM need an additional command after "inspect" and "show", which is missing in the documentation

use "show values" instead of just "show" or "inspect"
